import { BreedInfo } from './helpers';

export const CAT_BREEDS: BreedInfo[] = [
  {
    breed: 'Persian',
    sizes: ['MEDIUM'],
    colors: ['White', 'Black', 'Blue', 'Cream', 'Red', 'Silver', 'Calico'],
    temperaments: [
      ['quiet', 'gentle', 'affectionate'],
      ['calm', 'sweet', 'docile'],
      ['relaxed', 'dignified', 'placid'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/1au.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/dri.jpg', 'https://cdn2.thecatapi.com/images/e1g.jpg', 'https://cdn2.thecatapi.com/images/cjc.jpg'],
    ageRange: [1, 15],
    priceRange: [50, 2500],
  },
  {
    breed: 'Maine Coon',
    sizes: ['LARGE', 'EXTRA_LARGE'],
    colors: ['Brown Tabby', 'Black', 'Red', 'Silver', 'Cream', 'Blue'],
    temperaments: [
      ['gentle', 'intelligent', 'independent'],
      ['affectionate', 'playful', 'sociable'],
      ['friendly', 'easy_going', 'loyal'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/OOD3VXAQn.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/BQMSld0A0.jpg', 'https://cdn2.thecatapi.com/images/n1pLq-UYs.jpg', 'https://cdn2.thecatapi.com/images/_6x-3TiP4.jpg'],
    ageRange: [1, 13],
    priceRange: [75, 2000],
  },
  {
    breed: 'Ragdoll',
    sizes: ['LARGE'],
    colors: ['Seal Point', 'Blue Point', 'Chocolate Point', 'Lilac Point', 'Flame Point'],
    temperaments: [
      ['docile', 'calm', 'affectionate'],
      ['gentle', 'relaxed', 'easygoing'],
      ['loving', 'quiet', 'patient'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/oGefY4YoG.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/oGefY4YoG.jpg', 'https://cdn2.thecatapi.com/images/SxIKQ8Fph.jpg', 'https://cdn2.thecatapi.com/images/nn2JzkDzC.jpg'],
    ageRange: [1, 15],
    priceRange: [75, 2500],
  },
  {
    breed: 'British Shorthair',
    sizes: ['MEDIUM', 'LARGE'],
    colors: ['Blue', 'Lilac', 'Black', 'White', 'Cream', 'Tabby'],
    temperaments: [
      ['affectionate', 'easygoing', 'loyal'],
      ['calm', 'patient', 'gentle'],
      ['independent', 'quiet', 'devoted'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/s4wQPbsak.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/s4wQPbsak.jpg', 'https://cdn2.thecatapi.com/images/y61B6bFMf.jpg', 'https://cdn2.thecatapi.com/images/Hyq3DjLgc.jpg'],
    ageRange: [1, 15],
    priceRange: [75, 2000],
  },
  {
    breed: 'Siamese',
    sizes: ['MEDIUM'],
    colors: ['Seal Point', 'Blue Point', 'Chocolate Point', 'Lilac Point'],
    temperaments: [
      ['vocal', 'affectionate', 'social'],
      ['intelligent', 'playful', 'active'],
      ['curious', 'demanding', 'loyal'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/ai6Jps4sx.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/ai6Jps4sx.jpg', 'https://cdn2.thecatapi.com/images/h-KMbP2bQ.jpg', 'https://cdn2.thecatapi.com/images/0SxW2SQ_S.jpg'],
    ageRange: [1, 15],
    priceRange: [50, 1500],
  },
  {
    breed: 'Bengal',
    sizes: ['MEDIUM', 'LARGE'],
    colors: ['Brown Spotted', 'Silver Spotted', 'Snow', 'Charcoal'],
    temperaments: [
      ['energetic', 'playful', 'curious'],
      ['active', 'intelligent', 'agile'],
      ['alert', 'athletic', 'confident'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/O3btzLlsO.png',
    extraImages: ['https://cdn2.thecatapi.com/images/IFXsxIreu.jpg', 'https://cdn2.thecatapi.com/images/ByK5lf7E_.jpg', 'https://cdn2.thecatapi.com/images/4lCxx9MSI.jpg'],
    ageRange: [1, 14],
    priceRange: [100, 3000],
  },
  {
    breed: 'Abyssinian',
    sizes: ['MEDIUM'],
    colors: ['Ruddy', 'Red', 'Blue', 'Fawn'],
    temperaments: [
      ['active', 'playful', 'curious'],
      ['intelligent', 'loyal', 'social'],
      ['energetic', 'affectionate', 'adventurous'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg', 'https://cdn2.thecatapi.com/images/cUn0wsYEY.jpg', 'https://cdn2.thecatapi.com/images/-LFsAmJqn.jpg'],
    ageRange: [1, 14],
    priceRange: [75, 2000],
  },
  {
    breed: 'Scottish Fold',
    sizes: ['MEDIUM'],
    colors: ['White', 'Blue', 'Black', 'Red', 'Cream', 'Silver Tabby'],
    temperaments: [
      ['sweet', 'charming', 'gentle'],
      ['calm', 'adaptable', 'affectionate'],
      ['loyal', 'playful', 'quiet'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/o9t0LDcsa.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/o9t0LDcsa.jpg', 'https://cdn2.thecatapi.com/images/QJGJfRIBr.jpg', 'https://cdn2.thecatapi.com/images/nfU0o6pxu.jpg'],
    ageRange: [1, 14],
    priceRange: [75, 2000],
  },
  {
    breed: 'Sphynx',
    sizes: ['MEDIUM'],
    colors: ['White', 'Black', 'Blue', 'Red', 'Lavender', 'Chocolate'],
    temperaments: [
      ['extroverted', 'energetic', 'affectionate'],
      ['inquisitive', 'intelligent', 'friendly'],
      ['loving', 'social', 'loyal'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/BDb8ZXb1v.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/BDb8ZXb1v.jpg', 'https://cdn2.thecatapi.com/images/07b.jpg', 'https://cdn2.thecatapi.com/images/3kg.jpg'],
    ageRange: [1, 14],
    priceRange: [100, 3000],
  },
  {
    breed: 'Russian Blue',
    sizes: ['MEDIUM'],
    colors: ['Blue', 'Silver Blue'],
    temperaments: [
      ['gentle', 'quiet', 'shy'],
      ['intelligent', 'curious', 'reserved'],
      ['loyal', 'sensitive', 'calm'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/Rhj-JLq-Q.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/Rhj-JLq-Q.jpg', 'https://cdn2.thecatapi.com/images/b4S0E3t5v.jpg', 'https://cdn2.thecatapi.com/images/5AdhMjeEu.jpg'],
    ageRange: [1, 16],
    priceRange: [75, 2000],
  },
  {
    breed: 'Birman',
    sizes: ['MEDIUM', 'LARGE'],
    colors: ['Seal Point', 'Blue Point', 'Lilac Point', 'Chocolate Point'],
    temperaments: [
      ['gentle', 'affectionate', 'active'],
      ['social', 'calm', 'sweet'],
      ['loyal', 'playful', 'intelligent'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/HOrX5gcpY.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/HOrX5gcpY.jpg', 'https://cdn2.thecatapi.com/images/ai6Jps4sx.jpg', 'https://cdn2.thecatapi.com/images/SxIKQ8Fph.jpg'],
    ageRange: [1, 15],
    priceRange: [75, 2000],
  },
  {
    breed: 'Norwegian Forest Cat',
    sizes: ['LARGE'],
    colors: ['Brown Tabby', 'White', 'Black', 'Blue', 'Red', 'Cream'],
    temperaments: [
      ['gentle', 'friendly', 'intelligent'],
      ['independent', 'athletic', 'calm'],
      ['sweet', 'patient', 'adaptable'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/06btnGJBf.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/06btnGJBf.jpg', 'https://cdn2.thecatapi.com/images/OOD3VXAQn.jpg', 'https://cdn2.thecatapi.com/images/n1pLq-UYs.jpg'],
    ageRange: [1, 14],
    priceRange: [75, 1800],
  },
  {
    breed: 'Domestic Shorthair',
    sizes: ['SMALL', 'MEDIUM', 'LARGE'],
    colors: ['Tabby', 'Black', 'White', 'Orange', 'Calico', 'Tuxedo', 'Gray', 'Tortoiseshell'],
    temperaments: [
      ['friendly', 'adaptable', 'affectionate'],
      ['independent', 'curious', 'playful'],
      ['calm', 'social', 'sweet'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/bpc.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/bpc.jpg', 'https://cdn2.thecatapi.com/images/dri.jpg', 'https://cdn2.thecatapi.com/images/e1g.jpg'],
    ageRange: [1, 16],
    priceRange: [25, 150],
  },
  {
    breed: 'Domestic Longhair',
    sizes: ['SMALL', 'MEDIUM', 'LARGE'],
    colors: ['Tabby', 'Black', 'White', 'Orange', 'Calico', 'Gray', 'Tortoiseshell'],
    temperaments: [
      ['gentle', 'affectionate', 'laid_back'],
      ['friendly', 'independent', 'calm'],
      ['playful', 'curious', 'sweet'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/at7.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/at7.jpg', 'https://cdn2.thecatapi.com/images/cjc.jpg', 'https://cdn2.thecatapi.com/images/1au.jpg'],
    ageRange: [1, 16],
    priceRange: [25, 150],
  },
  {
    breed: 'Burmese',
    sizes: ['MEDIUM'],
    colors: ['Sable', 'Champagne', 'Blue', 'Platinum'],
    temperaments: [
      ['affectionate', 'playful', 'vocal'],
      ['social', 'curious', 'intelligent'],
      ['loving', 'trusting', 'active'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/4lCxx9MSI.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/4lCxx9MSI.jpg', 'https://cdn2.thecatapi.com/images/IFXsxIreu.jpg', 'https://cdn2.thecatapi.com/images/ByK5lf7E_.jpg'],
    ageRange: [1, 16],
    priceRange: [75, 1800],
  },
  {
    breed: 'Exotic Shorthair',
    sizes: ['MEDIUM'],
    colors: ['White', 'Blue', 'Black', 'Red', 'Cream', 'Silver Tabby'],
    temperaments: [
      ['affectionate', 'sweet', 'loyal'],
      ['calm', 'gentle', 'quiet'],
      ['playful', 'easygoing', 'peaceful'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/YnPrYEmfe.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/YnPrYEmfe.jpg', 'https://cdn2.thecatapi.com/images/1au.jpg', 'https://cdn2.thecatapi.com/images/dri.jpg'],
    ageRange: [1, 14],
    priceRange: [75, 2500],
  },
  {
    breed: 'American Shorthair',
    sizes: ['MEDIUM', 'LARGE'],
    colors: ['Silver Tabby', 'Brown Tabby', 'Black', 'White', 'Blue', 'Calico'],
    temperaments: [
      ['easygoing', 'calm', 'affectionate'],
      ['playful', 'adaptable', 'gentle'],
      ['sociable', 'good_natured', 'quiet'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/JFPROfGtQ.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/JFPROfGtQ.jpg', 'https://cdn2.thecatapi.com/images/Hyq3DjLgc.jpg', 'https://cdn2.thecatapi.com/images/y61B6bFMf.jpg'],
    ageRange: [1, 15],
    priceRange: [50, 1200],
  },
  {
    breed: 'Tonkinese',
    sizes: ['MEDIUM'],
    colors: ['Natural Mink', 'Champagne Mink', 'Blue Mink', 'Platinum Mink'],
    temperaments: [
      ['active', 'playful', 'social'],
      ['intelligent', 'vocal', 'affectionate'],
      ['curious', 'friendly', 'outgoing'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/KBroiVNCM.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/KBroiVNCM.jpg', 'https://cdn2.thecatapi.com/images/h-KMbP2bQ.jpg', 'https://cdn2.thecatapi.com/images/0SxW2SQ_S.jpg'],
    ageRange: [1, 14],
    priceRange: [50, 1500],
  },
  {
    breed: 'Savannah',
    sizes: ['LARGE', 'EXTRA_LARGE'],
    colors: ['Brown Spotted Tabby', 'Silver Spotted Tabby', 'Black', 'Smoke'],
    temperaments: [
      ['curious', 'social', 'assertive'],
      ['active', 'adventurous', 'loyal'],
      ['intelligent', 'energetic', 'bold'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/IG8AJurjS.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/IG8AJurjS.jpg', 'https://cdn2.thecatapi.com/images/O3btzLlsO.png', 'https://cdn2.thecatapi.com/images/IFXsxIreu.jpg'],
    ageRange: [1, 17],
    priceRange: [100, 5000],
  },
  {
    breed: 'Himalayan',
    sizes: ['MEDIUM', 'LARGE'],
    colors: ['Seal Point', 'Blue Point', 'Flame Point', 'Cream Point'],
    temperaments: [
      ['calm', 'gentle', 'devoted'],
      ['sweet', 'quiet', 'affectionate'],
      ['docile', 'sociable', 'serene'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/CDhOtM-Ig.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/CDhOtM-Ig.jpg', 'https://cdn2.thecatapi.com/images/1au.jpg', 'https://cdn2.thecatapi.com/images/e1g.jpg'],
    ageRange: [1, 14],
    priceRange: [75, 2500],
  },
  {
    breed: 'Devon Rex',
    sizes: ['SMALL'],
    colors: ['White', 'Black', 'Blue', 'Chocolate', 'Cinnamon', 'Lavender'],
    temperaments: [
      ['playful', 'mischievous', 'people_oriented'],
      ['active', 'intelligent', 'social'],
      ['affectionate', 'lively', 'loyal'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/4RBiOtFOh.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/4RBiOtFOh.jpg', 'https://cdn2.thecatapi.com/images/07b.jpg', 'https://cdn2.thecatapi.com/images/3kg.jpg'],
    ageRange: [1, 14],
    priceRange: [75, 2000],
  },
  {
    breed: 'Cornish Rex',
    sizes: ['SMALL', 'MEDIUM'],
    colors: ['White', 'Black', 'Blue', 'Red', 'Cream', 'Chocolate'],
    temperaments: [
      ['adventurous', 'intelligent', 'social'],
      ['playful', 'active', 'curious'],
      ['affectionate', 'gentle', 'kitten_like'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/unPP08xOZ.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/unPP08xOZ.jpg', 'https://cdn2.thecatapi.com/images/4RBiOtFOh.jpg', 'https://cdn2.thecatapi.com/images/BDb8ZXb1v.jpg'],
    ageRange: [1, 15],
    priceRange: [75, 1800],
  },
  {
    breed: 'Ragamuffin',
    sizes: ['LARGE'],
    colors: ['White', 'Black', 'Blue', 'Brown', 'Cinnamon', 'Cream'],
    temperaments: [
      ['friendly', 'sweet', 'patient'],
      ['calm', 'docile', 'affectionate'],
      ['gentle', 'loving', 'devoted'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/SMuZx-bFM.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/SMuZx-bFM.jpg', 'https://cdn2.thecatapi.com/images/oGefY4YoG.jpg', 'https://cdn2.thecatapi.com/images/nn2JzkDzC.jpg'],
    ageRange: [1, 15],
    priceRange: [75, 2000],
  },
  {
    breed: 'Bombay',
    sizes: ['MEDIUM'],
    colors: ['Black'],
    temperaments: [
      ['affectionate', 'social', 'playful'],
      ['intelligent', 'gentle', 'adaptable'],
      ['loving', 'outgoing', 'curious'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/5iYq9NmT1.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/5iYq9NmT1.jpg', 'https://cdn2.thecatapi.com/images/QJGJfRIBr.jpg', 'https://cdn2.thecatapi.com/images/nfU0o6pxu.jpg'],
    ageRange: [1, 15],
    priceRange: [50, 1500],
  },
  {
    breed: 'Turkish Angora',
    sizes: ['MEDIUM'],
    colors: ['White', 'Black', 'Blue', 'Red', 'Cream', 'Silver Tabby'],
    temperaments: [
      ['playful', 'athletic', 'intelligent'],
      ['affectionate', 'social', 'gentle'],
      ['graceful', 'energetic', 'devoted'],
    ],
    imageUrl: 'https://cdn2.thecatapi.com/images/7CGV4WVFq.jpg',
    extraImages: ['https://cdn2.thecatapi.com/images/7CGV4WVFq.jpg', 'https://cdn2.thecatapi.com/images/b4S0E3t5v.jpg', 'https://cdn2.thecatapi.com/images/5AdhMjeEu.jpg'],
    ageRange: [1, 15],
    priceRange: [50, 2000],
  },
];

export const CAT_NAMES = [
  'Luna', 'Milo', 'Oliver', 'Bella', 'Leo', 'Lily', 'Charlie', 'Cleo',
  'Simba', 'Nala', 'Max', 'Lucy', 'Loki', 'Chloe', 'Jasper', 'Willow',
  'Oreo', 'Kitty', 'Oscar', 'Daisy', 'Smokey', 'Rosie', 'Tiger', 'Pepper',
  'Shadow', 'Ginger', 'Salem', 'Coco', 'Felix', 'Misty', 'Mochi', 'Peanut',
  'Binx', 'Maple', 'Ziggy', 'Olive', 'Biscuit', 'Pearl', 'Finn', 'Hazel',
  'Toby', 'Stella', 'Bear', 'Poppy', 'Theo', 'Ellie', 'Archie', 'Sophie',
  'Boots', 'Ivy', 'Mittens', 'Ruby', 'Whiskers', 'Athena', 'Patches', 'Sage',
  'Bandit', 'Freya', 'Tux', 'Zelda', 'Pumpkin', 'Callie', 'Ash', 'Clover',
];

export const CAT_DESCRIPTIONS = [
  (name: string, breed: string, age: number) =>
    `${name} is a ${age}-year-old ${breed} who loves sunny windowsills and gentle head scratches. A purr machine who will warm your heart.`,
  (name: string, breed: string, age: number) =>
    `Meet ${name}, an adorable ${age}-year-old ${breed}. This sweet kitty enjoys playing with feather toys and curling up in your lap.`,
  (name: string, breed: string, age: number) =>
    `${name} is a gorgeous ${age}-year-old ${breed} with a calm and loving personality. Does well in quiet homes and loves being around people.`,
  (name: string, breed: string, age: number) =>
    `Say hello to ${name}! This ${age}-year-old ${breed} is litter-trained, up to date on vaccines, and ready to find a loving forever home.`,
  (name: string, breed: string, age: number) =>
    `${name} is a playful ${age}-year-old ${breed} who brings joy to everyone. Loves interactive toys and will follow you room to room.`,
  (name: string, breed: string, age: number) =>
    `Looking for a feline companion? ${name} is a gentle ${age}-year-old ${breed} who bonds deeply with their owner and enjoys quiet evenings together.`,
  (name: string, breed: string, age: number) =>
    `${name}, a stunning ${age}-year-old ${breed}, is looking for the purrfect family. Known for their sweet demeanor and photogenic looks.`,
  (name: string, breed: string, age: number) =>
    `This charming ${age}-year-old ${breed} named ${name} has a personality as beautiful as their coat. Friendly and affectionate from day one.`,
];
