import { BreedInfo } from './helpers';

export const DOG_BREEDS: BreedInfo[] = [
  {
    breed: 'Golden Retriever',
    sizes: ['LARGE'],
    colors: ['Golden', 'Light Golden', 'Dark Golden', 'Cream'],
    temperaments: [
      ['friendly', 'reliable', 'trustworthy'],
      ['playful', 'gentle', 'good_with_kids'],
      ['intelligent', 'devoted', 'active'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1633722715463-d30f4f325e24?w=800',
    ageRange: [1, 10],
    priceRange: [300, 2500],
  },
  {
    breed: 'Labrador Retriever',
    sizes: ['LARGE'],
    colors: ['Yellow', 'Black', 'Chocolate'],
    temperaments: [
      ['friendly', 'active', 'outgoing'],
      ['gentle', 'agile', 'intelligent'],
      ['trusting', 'even_tempered', 'kind'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1579296061519-2904c46dce15?w=800',
    ageRange: [1, 12],
    priceRange: [300, 2000],
  },
  {
    breed: 'German Shepherd',
    sizes: ['LARGE'],
    colors: ['Black and Tan', 'Sable', 'All Black', 'Black and Red'],
    temperaments: [
      ['confident', 'courageous', 'smart'],
      ['loyal', 'obedient', 'watchful'],
      ['alert', 'fearless', 'eager_to_learn'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=800',
    ageRange: [1, 10],
    priceRange: [500, 3000],
  },
  {
    breed: 'French Bulldog',
    sizes: ['SMALL'],
    colors: ['Brindle', 'Fawn', 'White', 'Cream', 'Blue'],
    temperaments: [
      ['adaptable', 'playful', 'smart'],
      ['affectionate', 'easygoing', 'sociable'],
      ['alert', 'patient', 'lively'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1583337130417-13104dec14a3?w=800',
    ageRange: [1, 10],
    priceRange: [1500, 5000],
  },
  {
    breed: 'Bulldog',
    sizes: ['MEDIUM'],
    colors: ['White', 'Fawn', 'Brindle', 'Red', 'Piebald'],
    temperaments: [
      ['docile', 'willful', 'friendly'],
      ['gregarious', 'calm', 'courageous'],
      ['loyal', 'gentle', 'loving'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1583512603805-3cc6b41f3edb?w=800',
    ageRange: [1, 8],
    priceRange: [1000, 4000],
  },
  {
    breed: 'Poodle',
    sizes: ['SMALL', 'MEDIUM', 'LARGE'],
    colors: ['White', 'Black', 'Apricot', 'Brown', 'Silver', 'Red'],
    temperaments: [
      ['intelligent', 'active', 'alert'],
      ['faithful', 'trainable', 'instinctual'],
      ['elegant', 'proud', 'clever'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1616149005244-06e4ff4a5e04?w=800',
    ageRange: [1, 15],
    priceRange: [600, 3000],
  },
  {
    breed: 'Beagle',
    sizes: ['SMALL', 'MEDIUM'],
    colors: ['Tri-color', 'Lemon', 'Red and White', 'Chocolate Tri'],
    temperaments: [
      ['amiable', 'determined', 'excitable'],
      ['gentle', 'even_tempered', 'intelligent'],
      ['merry', 'curious', 'friendly'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=800',
    ageRange: [1, 12],
    priceRange: [400, 1500],
  },
  {
    breed: 'Rottweiler',
    sizes: ['LARGE', 'EXTRA_LARGE'],
    colors: ['Black and Mahogany', 'Black and Tan', 'Black and Rust'],
    temperaments: [
      ['loyal', 'confident', 'courageous'],
      ['good_natured', 'placid', 'devoted'],
      ['alert', 'fearless', 'obedient'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1567752881298-894bb81f9379?w=800',
    ageRange: [1, 9],
    priceRange: [600, 2500],
  },
  {
    breed: 'Yorkshire Terrier',
    sizes: ['TINY'],
    colors: ['Blue and Tan', 'Black and Gold', 'Steel Blue and Tan'],
    temperaments: [
      ['bold', 'confident', 'courageous'],
      ['intelligent', 'spirited', 'affectionate'],
      ['feisty', 'sprightly', 'tomboyish'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1615751072497-5f5169febe17?w=800',
    ageRange: [1, 13],
    priceRange: [800, 3000],
  },
  {
    breed: 'Dachshund',
    sizes: ['TINY', 'SMALL'],
    colors: ['Red', 'Black and Tan', 'Chocolate and Tan', 'Cream', 'Dapple'],
    temperaments: [
      ['clever', 'stubborn', 'devoted'],
      ['lively', 'courageous', 'playful'],
      ['curious', 'brave', 'spunky'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1612195583950-b8fd34c87093?w=800',
    ageRange: [1, 14],
    priceRange: [500, 2000],
  },
  {
    breed: 'Boxer',
    sizes: ['LARGE'],
    colors: ['Fawn', 'Brindle', 'White'],
    temperaments: [
      ['playful', 'energetic', 'loyal'],
      ['bright', 'fun_loving', 'active'],
      ['devoted', 'fearless', 'confident'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1543071220-6ee5bf71a54e?w=800',
    ageRange: [1, 10],
    priceRange: [700, 2500],
  },
  {
    breed: 'Siberian Husky',
    sizes: ['MEDIUM', 'LARGE'],
    colors: ['Black and White', 'Gray and White', 'Red and White', 'Sable and White', 'All White'],
    temperaments: [
      ['outgoing', 'mischievous', 'loyal'],
      ['friendly', 'gentle', 'alert'],
      ['intelligent', 'independent', 'adventurous'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1605568427561-40dd23c2acea?w=800',
    ageRange: [1, 12],
    priceRange: [600, 2000],
  },
  {
    breed: 'Great Dane',
    sizes: ['EXTRA_LARGE'],
    colors: ['Fawn', 'Brindle', 'Blue', 'Black', 'Harlequin', 'Mantle'],
    temperaments: [
      ['friendly', 'patient', 'dependable'],
      ['gentle', 'devoted', 'reserved'],
      ['loving', 'confident', 'spirited'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1620657096324-5765f1abb519?w=800',
    ageRange: [1, 8],
    priceRange: [1000, 3000],
  },
  {
    breed: 'Doberman Pinscher',
    sizes: ['LARGE'],
    colors: ['Black and Rust', 'Red and Rust', 'Blue and Rust', 'Fawn and Rust'],
    temperaments: [
      ['loyal', 'fearless', 'alert'],
      ['intelligent', 'energetic', 'obedient'],
      ['determined', 'confident', 'watchful'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1608667508764-33cf0726b13a?w=800',
    ageRange: [1, 10],
    priceRange: [1000, 2500],
  },
  {
    breed: 'Shih Tzu',
    sizes: ['TINY', 'SMALL'],
    colors: ['Gold and White', 'Black and White', 'Brindle', 'Liver', 'Red and White'],
    temperaments: [
      ['affectionate', 'playful', 'outgoing'],
      ['loyal', 'gentle', 'happy'],
      ['clever', 'lively', 'friendly'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1586671267731-da2cf3ceeb80?w=800',
    ageRange: [1, 14],
    priceRange: [500, 2000],
  },
  {
    breed: 'Miniature Schnauzer',
    sizes: ['SMALL'],
    colors: ['Salt and Pepper', 'Black', 'Black and Silver', 'White'],
    temperaments: [
      ['friendly', 'smart', 'obedient'],
      ['alert', 'spirited', 'fearless'],
      ['affectionate', 'active', 'trainable'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1599312804043-37249aa2ab89?w=800',
    ageRange: [1, 14],
    priceRange: [600, 2500],
  },
  {
    breed: 'Australian Shepherd',
    sizes: ['MEDIUM', 'LARGE'],
    colors: ['Blue Merle', 'Red Merle', 'Black Tri', 'Red Tri'],
    temperaments: [
      ['smart', 'work_oriented', 'exuberant'],
      ['good_natured', 'active', 'protective'],
      ['loyal', 'agile', 'attentive'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1561495376-dc9c7c5b8726?w=800',
    ageRange: [1, 13],
    priceRange: [600, 2000],
  },
  {
    breed: 'Cavalier King Charles Spaniel',
    sizes: ['SMALL'],
    colors: ['Blenheim', 'Tricolor', 'Black and Tan', 'Ruby'],
    temperaments: [
      ['affectionate', 'gentle', 'graceful'],
      ['patient', 'adaptable', 'fearless'],
      ['sociable', 'playful', 'eager'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1615233500064-caa995e2f9dd?w=800',
    ageRange: [1, 12],
    priceRange: [1000, 3500],
  },
  {
    breed: 'Pomeranian',
    sizes: ['TINY'],
    colors: ['Orange', 'Black', 'White', 'Cream', 'Sable', 'Blue'],
    temperaments: [
      ['lively', 'bold', 'inquisitive'],
      ['playful', 'friendly', 'active'],
      ['sociable', 'intelligent', 'extroverted'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800',
    ageRange: [1, 14],
    priceRange: [800, 3000],
  },
  {
    breed: 'Pembroke Welsh Corgi',
    sizes: ['SMALL', 'MEDIUM'],
    colors: ['Red', 'Sable', 'Fawn', 'Tri-color', 'Black and Tan'],
    temperaments: [
      ['playful', 'bold', 'friendly'],
      ['tenacious', 'protective', 'outgoing'],
      ['intelligent', 'alert', 'affectionate'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1612536057832-2ff7ead58194?w=800',
    ageRange: [1, 13],
    priceRange: [1000, 2500],
  },
  {
    breed: 'Bernese Mountain Dog',
    sizes: ['LARGE', 'EXTRA_LARGE'],
    colors: ['Tri-color (Black, White, Rust)'],
    temperaments: [
      ['good_natured', 'calm', 'strong'],
      ['affectionate', 'faithful', 'intelligent'],
      ['loyal', 'gentle', 'patient'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1587316745247-a2c828a43ed5?w=800',
    ageRange: [1, 8],
    priceRange: [1500, 4000],
  },
  {
    breed: 'Havanese',
    sizes: ['TINY', 'SMALL'],
    colors: ['White', 'Black', 'Havana Brown', 'Tobacco', 'Fawn'],
    temperaments: [
      ['playful', 'intelligent', 'outgoing'],
      ['companionable', 'responsive', 'gentle'],
      ['happy', 'lively', 'affectionate'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1535930749574-1399327ce78f?w=800',
    ageRange: [1, 14],
    priceRange: [1000, 2500],
  },
  {
    breed: 'Cocker Spaniel',
    sizes: ['MEDIUM'],
    colors: ['Black', 'Golden', 'Red', 'Brown', 'Parti-color'],
    temperaments: [
      ['gentle', 'smart', 'happy'],
      ['merry', 'trustworthy', 'faithful'],
      ['joyful', 'playful', 'active'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1594922009922-d10848fa6f0e?w=800',
    ageRange: [1, 12],
    priceRange: [600, 2000],
  },
  {
    breed: 'Border Collie',
    sizes: ['MEDIUM'],
    colors: ['Black and White', 'Red and White', 'Blue Merle', 'Tri-color'],
    temperaments: [
      ['tenacious', 'keen', 'energetic'],
      ['intelligent', 'responsive', 'alert'],
      ['athletic', 'loyal', 'hardworking'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1503256207526-0d5d80fa2f47?w=800',
    ageRange: [1, 14],
    priceRange: [600, 2000],
  },
  {
    breed: 'Maltese',
    sizes: ['TINY'],
    colors: ['White', 'White with Lemon'],
    temperaments: [
      ['playful', 'charming', 'gentle'],
      ['affectionate', 'docile', 'lively'],
      ['responsive', 'trusting', 'easygoing'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1618265341355-d0e2e6a9dfd4?w=800',
    ageRange: [1, 15],
    priceRange: [600, 2500],
  },
  {
    breed: 'Chihuahua',
    sizes: ['TINY'],
    colors: ['Fawn', 'Black', 'White', 'Chocolate', 'Cream', 'Gold'],
    temperaments: [
      ['charming', 'graceful', 'sassy'],
      ['devoted', 'lively', 'alert'],
      ['quick', 'courageous', 'spirited'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1583337130417-13104dec14a3?w=800',
    ageRange: [1, 16],
    priceRange: [400, 1500],
  },
  {
    breed: 'Vizsla',
    sizes: ['MEDIUM', 'LARGE'],
    colors: ['Golden', 'Golden Rust', 'Red Golden'],
    temperaments: [
      ['gentle', 'affectionate', 'energetic'],
      ['loyal', 'quiet', 'protective'],
      ['athletic', 'eager', 'loving'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1549297161-14f79605a74c?w=800',
    ageRange: [1, 12],
    priceRange: [1000, 2500],
  },
  {
    breed: 'Weimaraner',
    sizes: ['LARGE'],
    colors: ['Silver Gray', 'Mouse Gray', 'Blue'],
    temperaments: [
      ['friendly', 'fearless', 'obedient'],
      ['alert', 'steady', 'energetic'],
      ['intelligent', 'powerful', 'aloof'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1610041518868-f6297569dab7?w=800',
    ageRange: [1, 11],
    priceRange: [700, 2000],
  },
  {
    breed: 'Shetland Sheepdog',
    sizes: ['SMALL', 'MEDIUM'],
    colors: ['Sable', 'Tri-color', 'Blue Merle', 'Bi-black'],
    temperaments: [
      ['playful', 'energetic', 'bright'],
      ['intelligent', 'eager', 'reserved'],
      ['affectionate', 'loyal', 'responsive'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1595429035839-c99c298ffdde?w=800',
    ageRange: [1, 13],
    priceRange: [800, 2000],
  },
  {
    breed: 'English Springer Spaniel',
    sizes: ['MEDIUM'],
    colors: ['Black and White', 'Liver and White', 'Blue Roan'],
    temperaments: [
      ['friendly', 'playful', 'obedient'],
      ['attentive', 'active', 'cheerful'],
      ['affectionate', 'gentle', 'social'],
    ],
    imageUrl: 'https://images.unsplash.com/photo-1585559604830-7d9ebd32a903?w=800',
    ageRange: [1, 14],
    priceRange: [600, 2000],
  },
];

export const DOG_NAMES = [
  'Max', 'Buddy', 'Charlie', 'Cooper', 'Rocky', 'Bear', 'Duke', 'Tucker',
  'Jack', 'Oliver', 'Milo', 'Leo', 'Finn', 'Zeus', 'Bentley', 'Winston',
  'Teddy', 'Archie', 'Toby', 'Rusty', 'Louie', 'Beau', 'Harley', 'Bruno',
  'Murphy', 'Oscar', 'Hank', 'Jasper', 'Gus', 'Otis', 'Rex', 'Apollo',
  'Bella', 'Luna', 'Daisy', 'Lucy', 'Sadie', 'Molly', 'Maggie', 'Bailey',
  'Sophie', 'Chloe', 'Stella', 'Penny', 'Zoey', 'Lola', 'Willow', 'Rosie',
  'Ruby', 'Nala', 'Gracie', 'Ellie', 'Coco', 'Hazel', 'Roxy', 'Piper',
  'Winnie', 'Millie', 'Ginger', 'Dixie', 'Pepper', 'Ivy', 'Honey', 'Scout',
];

export const DOG_DESCRIPTIONS = [
  (name: string, breed: string, age: number) =>
    `${name} is a ${age}-year-old ${breed} who loves nothing more than a good game of fetch and belly rubs. Well-socialized and great with families.`,
  (name: string, breed: string, age: number) =>
    `Meet ${name}! This adorable ${age}-year-old ${breed} is looking for a forever home. Fully trained and ready to bring joy to your household.`,
  (name: string, breed: string, age: number) =>
    `${name} is a wonderful ${age}-year-old ${breed} with a heart of gold. Loves walks in the park and cuddling on the couch.`,
  (name: string, breed: string, age: number) =>
    `Say hello to ${name}, a charming ${age}-year-old ${breed}. This sweet pup is house-trained, up to date on vaccinations, and ready for adoption.`,
  (name: string, breed: string, age: number) =>
    `${name} is an energetic ${age}-year-old ${breed} who thrives on activity and companionship. Great with other dogs and children.`,
  (name: string, breed: string, age: number) =>
    `Looking for a loyal companion? ${name} is a gentle ${age}-year-old ${breed} who bonds deeply with their family. Very well-behaved and affectionate.`,
  (name: string, breed: string, age: number) =>
    `${name}, a beautiful ${age}-year-old ${breed}, is searching for the perfect family. Known for being playful, obedient, and incredibly loving.`,
  (name: string, breed: string, age: number) =>
    `This ${age}-year-old ${breed} named ${name} has a personality that will steal your heart. Friendly with everyone and always eager to please.`,
];
