export interface OrgData {
  legalName: string;
  publicName: string;
  organizationType: 'BREEDER' | 'SHELTER' | 'HUMANE_SOCIETY' | 'RESCUE' | 'NONPROFIT' | 'FOSTER_NETWORK';
  description: string;
  websiteUrl: string;
  phone: string;
  email: string;
  addressLine1: string;
  city: string;
  region: string;
  postalCode: string;
  country: string;
  latitude: number;
  longitude: number;
}

export const ORGANIZATIONS: OrgData[] = [
  { legalName: 'Happy Paws Animal Shelter Inc', publicName: 'Happy Paws Shelter', organizationType: 'SHELTER', description: 'A trusted local animal shelter dedicated to finding forever homes for dogs, cats, and birds.', websiteUrl: 'https://happypaws.example.com', phone: '+15035551001', email: 'info@happypaws.example.com', addressLine1: '1234 SE Hawthorne Blvd', city: 'Portland', region: 'OR', postalCode: '97214', country: 'US', latitude: 45.5152, longitude: -122.6784 },
  { legalName: 'Sunrise Breeders LLC', publicName: 'Sunrise Breeders', organizationType: 'BREEDER', description: 'Family-owned breeder specializing in Golden Retrievers and Labrador Retrievers since 1995.', websiteUrl: 'https://sunrisebreeders.example.com', phone: '+12065551002', email: 'info@sunrisebreeders.example.com', addressLine1: '5678 NW Market St', city: 'Seattle', region: 'WA', postalCode: '98107', country: 'US', latitude: 47.6062, longitude: -122.3321 },
  { legalName: 'Second Chance Rescue Foundation', publicName: 'Second Chance Rescue', organizationType: 'RESCUE', description: 'Nonprofit rescue dedicated to saving abandoned and surrendered pets in the greater LA area.', websiteUrl: 'https://secondchancerescue.example.com', phone: '+13105551003', email: 'help@secondchancerescue.example.com', addressLine1: '900 Wilshire Blvd', city: 'Los Angeles', region: 'CA', postalCode: '90017', country: 'US', latitude: 34.0522, longitude: -118.2437 },
  { legalName: 'Mountain View Humane Society', publicName: 'Mountain View Humane', organizationType: 'HUMANE_SOCIETY', description: 'Serving the Denver metro area with adoption, education, and community outreach programs.', websiteUrl: 'https://mvhumane.example.com', phone: '+13035551004', email: 'adopt@mvhumane.example.com', addressLine1: '2100 E Colfax Ave', city: 'Denver', region: 'CO', postalCode: '80206', country: 'US', latitude: 39.7392, longitude: -104.9903 },
  { legalName: 'Feathered Friends Aviary LLC', publicName: 'Feathered Friends', organizationType: 'BREEDER', description: 'Specialized avian breeder with hand-raised parrots, cockatiels, and exotic birds.', websiteUrl: 'https://featheredfriends.example.com', phone: '+15125551005', email: 'birds@featheredfriends.example.com', addressLine1: '456 S Congress Ave', city: 'Austin', region: 'TX', postalCode: '78704', country: 'US', latitude: 30.2672, longitude: -97.7431 },
  { legalName: 'Purrfect Match Cat Rescue Inc', publicName: 'Purrfect Match', organizationType: 'RESCUE', description: 'All-volunteer cat rescue finding loving homes for stray and surrendered felines.', websiteUrl: 'https://purrfectmatch.example.com', phone: '+17735551006', email: 'adopt@purrfectmatch.example.com', addressLine1: '3200 N Halsted St', city: 'Chicago', region: 'IL', postalCode: '60657', country: 'US', latitude: 41.8781, longitude: -87.6298 },
  { legalName: 'Loyal Companions Breeding Co', publicName: 'Loyal Companions', organizationType: 'BREEDER', description: 'AKC-registered breeder of German Shepherds, Dobermans, and Rottweilers with health guarantees.', websiteUrl: 'https://loyalcompanions.example.com', phone: '+16025551007', email: 'info@loyalcompanions.example.com', addressLine1: '7890 E Camelback Rd', city: 'Phoenix', region: 'AZ', postalCode: '85251', country: 'US', latitude: 33.4484, longitude: -111.9490 },
  { legalName: 'Evergreen Animal Rescue Society', publicName: 'Evergreen Rescue', organizationType: 'RESCUE', description: 'Community-based rescue providing foster care, medical treatment, and rehoming services.', websiteUrl: 'https://evergreenrescue.example.com', phone: '+14255551008', email: 'foster@evergreenrescue.example.com', addressLine1: '345 108th Ave NE', city: 'Bellevue', region: 'WA', postalCode: '98004', country: 'US', latitude: 47.6101, longitude: -122.2015 },
  { legalName: 'Tiny Paws Toy Breed Specialists LLC', publicName: 'Tiny Paws', organizationType: 'BREEDER', description: 'Boutique breeder specializing in toy breeds including Yorkies, Shih Tzus, and Pomeranians.', websiteUrl: 'https://tinypaws.example.com', phone: '+14045551009', email: 'puppies@tinypaws.example.com', addressLine1: '1550 Peachtree St NE', city: 'Atlanta', region: 'GA', postalCode: '30309', country: 'US', latitude: 33.7490, longitude: -84.3880 },
  { legalName: 'Bay Area Humane Society', publicName: 'Bay Area Humane', organizationType: 'HUMANE_SOCIETY', description: 'Full-service humane society providing adoption, veterinary care, and humane education.', websiteUrl: 'https://bayareahumane.example.com', phone: '+14155551010', email: 'info@bayareahumane.example.com', addressLine1: '200 Alabama St', city: 'San Francisco', region: 'CA', postalCode: '94103', country: 'US', latitude: 37.7749, longitude: -122.4194 },
  { legalName: 'Wings of Love Bird Sanctuary Inc', publicName: 'Wings of Love', organizationType: 'NONPROFIT', description: 'Nonprofit sanctuary rehabilitating and rehoming surrendered and rescued exotic birds.', websiteUrl: 'https://wingsoflove.example.com', phone: '+13055551011', email: 'sanctuary@wingsoflove.example.com', addressLine1: '8200 SW 40th St', city: 'Miami', region: 'FL', postalCode: '33155', country: 'US', latitude: 25.7617, longitude: -80.1918 },
  { legalName: 'Heartland Foster Network', publicName: 'Heartland Fosters', organizationType: 'FOSTER_NETWORK', description: 'Network of foster families providing temporary care for pets awaiting permanent homes.', websiteUrl: 'https://heartlandfosters.example.com', phone: '+16125551012', email: 'fosters@heartlandfosters.example.com', addressLine1: '100 Nicollet Mall', city: 'Minneapolis', region: 'MN', postalCode: '55401', country: 'US', latitude: 44.9778, longitude: -93.2650 },
  { legalName: 'Premier Pedigree Kennels LLC', publicName: 'Premier Pedigree', organizationType: 'BREEDER', description: 'Champion-line breeder of Poodles, Bulldogs, and French Bulldogs with genetic testing.', websiteUrl: 'https://premierpedigree.example.com', phone: '+16175551013', email: 'pups@premierpedigree.example.com', addressLine1: '750 Boylston St', city: 'Boston', region: 'MA', postalCode: '02116', country: 'US', latitude: 42.3601, longitude: -71.0589 },
  { legalName: 'Desert Oasis Animal Shelter', publicName: 'Desert Oasis Shelter', organizationType: 'SHELTER', description: 'Open-admission shelter serving the Las Vegas community with adoption and spay/neuter programs.', websiteUrl: 'https://desertoasis.example.com', phone: '+17025551014', email: 'info@desertoasis.example.com', addressLine1: '655 N Mojave Rd', city: 'Las Vegas', region: 'NV', postalCode: '89101', country: 'US', latitude: 36.1699, longitude: -115.1398 },
  { legalName: 'Southern Charm Cavaliers LLC', publicName: 'Southern Charm', organizationType: 'BREEDER', description: 'Family breeder of Cavalier King Charles Spaniels and Cocker Spaniels in Nashville.', websiteUrl: 'https://southerncharm.example.com', phone: '+16155551015', email: 'info@southerncharm.example.com', addressLine1: '1000 Broadway', city: 'Nashville', region: 'TN', postalCode: '37203', country: 'US', latitude: 36.1627, longitude: -86.7816 },
  { legalName: 'Pacific Northwest Cat Alliance', publicName: 'PNW Cat Alliance', organizationType: 'RESCUE', description: 'Volunteer-run cat rescue with a trap-neuter-return program and community cat support.', websiteUrl: 'https://pnwcats.example.com', phone: '+15035551016', email: 'cats@pnwcats.example.com', addressLine1: '2345 NE Broadway', city: 'Portland', region: 'OR', postalCode: '97232', country: 'US', latitude: 45.5371, longitude: -122.6432 },
  { legalName: 'Carolina Bird Breeders Association', publicName: 'Carolina Birds', organizationType: 'BREEDER', description: 'Experienced aviculturists breeding healthy parakeets, canaries, finches, and lovebirds.', websiteUrl: 'https://carolinabirds.example.com', phone: '+19195551017', email: 'birds@carolinabirds.example.com', addressLine1: '400 Fayetteville St', city: 'Raleigh', region: 'NC', postalCode: '27601', country: 'US', latitude: 35.7796, longitude: -78.6382 },
  { legalName: 'Great Lakes Animal Welfare Foundation', publicName: 'Great Lakes Welfare', organizationType: 'NONPROFIT', description: 'Nonprofit providing veterinary assistance, pet food banks, and adoption services.', websiteUrl: 'https://greatlakeswelfare.example.com', phone: '+13135551018', email: 'help@greatlakeswelfare.example.com', addressLine1: '1001 Woodward Ave', city: 'Detroit', region: 'MI', postalCode: '48226', country: 'US', latitude: 42.3314, longitude: -83.0458 },
  { legalName: 'Rocky Mountain Parrot Rescue', publicName: 'RM Parrot Rescue', organizationType: 'RESCUE', description: 'Specialized parrot rescue rehabilitating and rehoming surrendered parrots of all species.', websiteUrl: 'https://rmparrotrescue.example.com', phone: '+13035551019', email: 'parrots@rmparrotrescue.example.com', addressLine1: '1600 Champa St', city: 'Denver', region: 'CO', postalCode: '80202', country: 'US', latitude: 39.7475, longitude: -104.9947 },
  { legalName: 'Sunshine State Shelters Inc', publicName: 'Sunshine Shelters', organizationType: 'SHELTER', description: 'Multi-location shelter network across Florida with a focus on reducing euthanasia rates.', websiteUrl: 'https://sunshineshelters.example.com', phone: '+18135551020', email: 'adopt@sunshineshelters.example.com', addressLine1: '500 E Kennedy Blvd', city: 'Tampa', region: 'FL', postalCode: '33602', country: 'US', latitude: 27.9506, longitude: -82.4572 },
  { legalName: 'Heritage Hound Breeders LLC', publicName: 'Heritage Hounds', organizationType: 'BREEDER', description: 'Responsible breeder of Beagles, Dachshunds, and Basset Hounds with health clearances.', websiteUrl: 'https://heritagehounds.example.com', phone: '+12155551021', email: 'hounds@heritagehounds.example.com', addressLine1: '1234 Market St', city: 'Philadelphia', region: 'PA', postalCode: '19107', country: 'US', latitude: 39.9526, longitude: -75.1652 },
  { legalName: 'Midwest Foster Friends Network', publicName: 'Midwest Fosters', organizationType: 'FOSTER_NETWORK', description: 'Coordinating foster placements for dogs, cats, and small animals across the Midwest.', websiteUrl: 'https://midwestfosters.example.com', phone: '+18165551022', email: 'foster@midwestfosters.example.com', addressLine1: '200 Main St', city: 'Kansas City', region: 'MO', postalCode: '64105', country: 'US', latitude: 39.0997, longitude: -94.5786 },
  { legalName: 'Emerald City Exotic Birds LLC', publicName: 'Emerald City Birds', organizationType: 'BREEDER', description: 'Premium breeder of macaws, cockatoos, and African Greys with lifetime support.', websiteUrl: 'https://emeraldcitybirds.example.com', phone: '+12065551023', email: 'exotics@emeraldcitybirds.example.com', addressLine1: '600 Pine St', city: 'Seattle', region: 'WA', postalCode: '98101', country: 'US', latitude: 47.6129, longitude: -122.3375 },
  { legalName: 'Golden Gate Humane Society', publicName: 'Golden Gate Humane', organizationType: 'HUMANE_SOCIETY', description: 'Comprehensive humane society with veterinary clinic, behavior training, and community programs.', websiteUrl: 'https://gghsociety.example.com', phone: '+14155551024', email: 'info@gghsociety.example.com', addressLine1: '2500 16th St', city: 'San Francisco', region: 'CA', postalCode: '94103', country: 'US', latitude: 37.7655, longitude: -122.4106 },
  { legalName: 'Lone Star Rescue Ranch', publicName: 'Lone Star Ranch', organizationType: 'RESCUE', description: 'Rural rescue ranch providing sanctuary for pets including dogs, cats, and farm birds.', websiteUrl: 'https://lonestarranch.example.com', phone: '+12145551025', email: 'ranch@lonestarranch.example.com', addressLine1: '4500 Cedar Springs Rd', city: 'Dallas', region: 'TX', postalCode: '75219', country: 'US', latitude: 32.7767, longitude: -96.7970 },
  { legalName: 'New England Cat Fanciers LLC', publicName: 'NE Cat Fanciers', organizationType: 'BREEDER', description: 'Registered breeder of Persians, Maine Coons, Ragdolls, and other pedigreed cats.', websiteUrl: 'https://necatfanciers.example.com', phone: '+18605551026', email: 'cats@necatfanciers.example.com', addressLine1: '55 Asylum St', city: 'Hartford', region: 'CT', postalCode: '06103', country: 'US', latitude: 41.7658, longitude: -72.6734 },
  { legalName: 'Aloha Pet Rescue Hawaii', publicName: 'Aloha Rescue', organizationType: 'RESCUE', description: 'Island rescue dedicated to finding homes for abandoned pets in the Hawaiian islands.', websiteUrl: 'https://aloharescue.example.com', phone: '+18085551027', email: 'aloha@aloharescue.example.com', addressLine1: '1000 Ala Moana Blvd', city: 'Honolulu', region: 'HI', postalCode: '96814', country: 'US', latitude: 21.3069, longitude: -157.8583 },
  { legalName: 'Capital City Animal Shelter', publicName: 'Capital City Shelter', organizationType: 'SHELTER', description: 'Municipal shelter providing intake, adoption, and rescue transfer services for the DC metro area.', websiteUrl: 'https://capitalcityshelter.example.com', phone: '+12025551028', email: 'adopt@capitalcityshelter.example.com', addressLine1: '1201 New York Ave NW', city: 'Washington', region: 'DC', postalCode: '20005', country: 'US', latitude: 38.9072, longitude: -77.0369 },
  { legalName: 'Northern Lights Sled Dog Breeders', publicName: 'Northern Lights K9', organizationType: 'BREEDER', description: 'Ethical breeder of Siberian Huskies, Bernese Mountain Dogs, and Great Danes.', websiteUrl: 'https://northernlightsk9.example.com', phone: '+19075551029', email: 'dogs@northernlightsk9.example.com', addressLine1: '320 W 5th Ave', city: 'Anchorage', region: 'AK', postalCode: '99501', country: 'US', latitude: 61.2181, longitude: -149.9003 },
  { legalName: 'Bayou Bird Haven Inc', publicName: 'Bayou Bird Haven', organizationType: 'NONPROFIT', description: 'Nonprofit avian sanctuary providing permanent care for unreleasable and surrendered birds.', websiteUrl: 'https://bayoubirdhaven.example.com', phone: '+15045551030', email: 'haven@bayoubirdhaven.example.com', addressLine1: '800 Poydras St', city: 'New Orleans', region: 'LA', postalCode: '70112', country: 'US', latitude: 29.9511, longitude: -90.0715 },
];
